### ISSUE TITLE
DRM and Vulkan should open the same GPU

### ISSUE THREAD

**Issue by st3r4g** [st3r4g/swvkc#18]
Right now for simplicity DRM and Vulkan open the GPU independently. This is a problem if the system has more than one GPU, because they might open different GPUs. I don't think it will ever make sense to have compositing GPU != displaying GPU. There are two possibilities:

1.  Open with DRM and tell Vulkan our choice
I think this is doable with mesa's recently added `device-select-layer`

2. Open with Vulkan and tell DRM our choice
This is not possible in core Vulkan, there is no way to extract the file descriptor or device node. However, the extension `VK_EXT_pci_bus_info` might provide enough info to be able to so.
EDIT: there will be a new extension `VK_EXT_physical_device_drm`

**Comment by Ella-0** [comment]
I think there might be some cases where compositing is not done on the displaying GPU. Possibly with dual GPU laptops where the different GPUs are wired to different outputs. For example, in my laptop the IGPU is wired to the integrated display where as the discrete GPU is wired to the HDMI port.

**Comment by st3r4g** [comment]
I'm not sure if it's possible/convenient to do so, because you'd have to pick a buffer format/modifier that the other GPU understands for scanout. Not sure if GBM can tell you this, and vendor-specific format are more optimized.

**Comment by Ella-0** [comment]
I think this is solved on Xorg, at lest for Intel/nvidia laptops with the nvidia card connected to the external display, by rendering to a virtual output and then using another piece of software to copy from that virtual output to the displaying GPU. At least that's my understanding from the `intel-virtual-output(4)` man page.

**Comment by st3r4g** [comment]
Yeah right it's what is called 'reverse PRIME' on X. So it should be possible with nouveau. But we can't use the proprietary driver until EGLStreams is implemented, or until mesa and nvidia agree on a common API to allocate buffers.

**Comment by Ella-0** [comment]
I've been looking into device-select-layer and it looks like there might be a couple ways one might handle it. First off device-select-layer only takes an integer to get the GPU so a way of knowing what that number will be is required. There's no way of passing a file descriptor or device node directly though we should be able to work out the index of the card and set the `MESA_VK_DEVICE_SELECT` variable before initialising Vulkan. Also do we need to deal with DRM directly? Doesn't Vulkan have `VK_KHR_display`? I'm guessing there is a reason for not using this however, if it was used, we wouldn't have to worry about selecting the GPU for DRM.

Setting `MESA_VK_DEVICE_SELECT=list` might be useful for debugging.

**Comment by st3r4g** [comment]
> Also do we need to deal with DRM directly? Doesn't Vulkan have `VK_KHR_display`? I'm guessing there is a reason for not using this however, if it was used, we wouldn't have to worry about selecting the GPU for DRM.

Using `VK_KHR_display` would have pros and cons. Biggest pro is that it would work even on proprietary nvidia drivers. It could also simplify some things, as the one you mentioned. But the big downside is that it's much more limited than doing DRM ourselves (unless they release more extensions). For example you can't manage planes, so you can't do direct scan-out of a fullscreen client or put a client on an overlay plane (these avoid an unnecessary vulkan composition step). Also you can't set other useful DRM properties.

So it's a tradeoff between optimizations+functionality and compatibility. If someone makes a `VK_KHR_display` backend for `swvkc` and it integrates reasonably well, I will accept it and make it a build-time switch.

**Comment by Ella-0** [comment]
I've implemented a basic compositor in rust with `VK_KHR_display` and a lot of things would have to be done differently i think so I don't think it'd be that feasible to implement here so that's out the window I guess.

**Comment by st3r4g** [comment]
Just saw that `VK_EXT_physical_device_drm` is being worked on

**Comment by Ella-0** [comment]
Oo, this is interesting. Good to know.

**Comment by Diegovsky** [comment]
The specification of `VK_EXT_physical_device_drm` is to be reviewed shortly: https://github.com/KhronosGroup/Vulkan-Docs/pull/1356

**Comment by Ella-0** [comment]
I'll start work on a pull to make use of it. There are already WIP MRs for radv, anv and v3dv.

**Comment by Ella-0** [comment]
`VK_EXT_physical_device_drm` has been merged now
